### PR TITLE
Kjt/premium details

### PR DESCRIPTION
**Pull request by taylorkj**
@srkirkland @jSylvestre : These changes should handle the multi-premium per gift scenario.

### CODE REVIEW

**Comment by jSylvestre** [comment]
@taylorkj Looks ok to me. I think I'll ignore displaying this information for now until we talk to them to see how they want it flattened.

**Comment by taylorkj** [comment]
Sounds good to me

**Comment by taylorkj** [comment]
I may just ignore populating it as well until then.

**Comment by srkirkland** [comment]
@taylorkj yup looks good to me too

**Pull request merged**
