### PR TITLE
Added IsActiveAllocation to help determine gift acceptance criteria

### PR DESCRIPTION
**Pull request by taylorkj**
Sorry Guys,  I should have added this along with the AllocationType.

### CODE REVIEW

**Comment by jSylvestre** [comment]
@taylorkj Looks good. Ship

**Comment by srkirkland** [comment]
@taylorkj i think it can just be isActive.  We know it is referring to the Allocation because that's what class it is in so it's redundant.

**Comment by taylorkj** [comment]
@srkirkland: Normally I'd agree with you, except you're going to need to pass it back to me in the KfsTransferRequest, so it will be out of context when not in the AllocationDetail if not prefixed with Allocation.

**Comment by srkirkland** [comment]
@taylorkj in the kfsTransferRequest you can call it isActiveAllocation.   Not in the giftModel.

**Comment by taylorkj** [comment]
@srkirkland :  still not sure I agree with you because Allocation is AllocationCode; Type is AllocationType, therefore, it seems reasonable that IsActive can also be IsActiveAllocation.

**Comment by srkirkland** [comment]
@taylorkj good point.  i'd change those too if i could.  But yea that ship has sailed for now, go ahead and leave it as is then.

**Comment by taylorkj** [comment]
@srkirkland:  I think it would make things easier if they had the same names for ease of one-to-one mapping when pulling the details directly out of the AllocationDetails object and sticking them directly into the KfsTransferRequest object.  IMHO

**Pull request merged**
