### PR TITLE
Added some MinLength and Required decorators to the KFS Account and Chart properties.  Then I can test to see if ModelState validation will catch bad KFS values.

### PR DESCRIPTION
**Pull request by taylorkj**
If this works, then we can skip adding discrete checks.

### CODE REVIEW

**Comment by jSylvestre** [comment]
@taylorkj Ship

**Comment by srkirkland** [comment]
@taylorkj looks good :shipit:

**Comment by jpknoll** [comment]
I'd rather have this type of functionality on the Giving Service.

**Comment by srkirkland** [comment]
@jpknoll how else would you extend the existing models w/ data annotations?

**Comment by jpknoll** [comment]
@srkirkland I wouldn't extend this model. Not all premiums will have account details. These models will be used for more than just processing in GivingService. @taylorkj can null check for a valid account when he's about to process the premium.

**Comment by srkirkland** [comment]
@jpknoll ah ok i thought you had some fancy way of having the givingService add data annotations to the model after the fact.  I think with partial classes and annotation metadata that can be done but not worth it.

**Pull request closed without merging**
