### PR TITLE
Changed "Benefiting"... to "Benefitting"...

### PR DESCRIPTION
**Pull request by taylorkj**

### CODE REVIEW

**Comment by taylorkj** [comment]
Had one of those odd words that had 2 correct spellings, but didn't match what was indicated on spreadsheet or in controller.

**Comment by jSylvestre** [comment]
@taylorkj :ship: And don't forget your sql ... :)

**Comment by taylorkj** [comment]
Actually, the SQL was correct.  That's how I noticed it.

**Comment by taylorkj** [comment]
It was coming back in the SQL, but not in the model.

**Comment by srkirkland** [comment]
@taylorkj ship!

**Pull request merged**
